changelog:
  exclude:
    labels:
      - dependencies
    authors:
      - octocat
  categories:
    - title: Fixed 🛠
      labels:
        - bug
    - title: Added 🎉
      labels:
        - feature
    - title: Changed
      labels:
        - "*"
